service: serverless-typescript-template
frameworkVersion: '3'

custom:
  stage: ${opt:stage, 'offline'}
  region: ${opt:region, 'us-east-1'}
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3001
    noPrependStageInUrl: true
    reloadHandler: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-1
  environment:
    STAGE: ${opt:stage}

functions:
  api:
    handler: src/handlers/api-handler.handler
    events:
      - httpApi:
          path: "/{proxy+}"
          method: "*"
    timeout: 30

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

package:
  include:
    - config/*.json
